[package]
name = "thepass"
version = "0.1.0"
edition = "2023_11"
description = "ThePass focused on enabling secure verification of data through Zero-Knowledge Proofs."
readme = "../README.md"
repository = "https://github.com/thepassid/ThePass"
license = "Apache-2.0"
keywords = ["Zero-Knowledge Proofs", "STARK proof", "verifier"]

[dependencies]
starknet = "2.8.4"
openzeppelin = "0.18.0"
"openzeppelin_access" = "0.18.0"
"openzeppelin_introspection" = "0.18.0"
"openzeppelin_token" = "0.18.0"
"openzeppelin_utils" = "0.18.0"
integrity = { path = "../../integrity" }

[dev-dependencies]
snforge_std = "0.31.0"
assert_macros = "2.8.4"
openzeppelin_testing = "0.18.0"

[[target.starknet-contract]]
casm = true
# sierra = true

[lib]
sierra = true
casm = false